version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver-container
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "@Password123!"
    ports:
      - "1433:1433" 
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - sql-network

  webapi:
    build:
      context: ./Curotec.backend
      dockerfile: Dockerfile
    container_name: webapi-container
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      DOTNET_RUNNING_IN_CONTAINER: "true" 
    ports:
      - "5000:80"
    depends_on:
      - sqlserver
    networks:
      - sql-network

  frontend:
    build:
      context: ./Curotec.frontend
      dockerfile: Dockerfile
    container_name: angular-container
    ports:
      - "4200:80"
    depends_on:
      - webapi
    networks:
      - sql-network

volumes:
  sqlserver-data:

networks:
  sql-network:
    driver: bridge
